In [1]:
#numpy libarary helps in stroring and computing lists
import numpy as np

In [2]:
#1-D array 
array=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
#geting element from spesific position
print('1st position',array[0])
print('5st position',array[4])
print('9st position',array[8])

1st position 1
5st position 5
9st position 9


In [4]:
#geting sub elements of array
print('1st position',array[0:1])
print('3rd position t0 5th position',array[2:5])
print('6st position t0 7nd position',array[5:7])
print('from start to 6th position',array[:6])

1st position [1]
3rd position t0 5th position [3 4 5]
6st position t0 7nd position [6 7]
from start to 6th position [1 2 3 4 5 6]


In [5]:
#geting size of array
print('size',array.size)

size 9


In [6]:
#finding min max and sum 
print('sum',array.sum())
print('max',array.max())
print('min',array.min())
#mean = 1+2+3+4+5+6+7+8+9 / 9
print('mean',array.mean())

sum 45
max 9
min 1
mean 5.0


In [7]:
#2-D array
arrays=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(arrays)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
#geting element from spesific position
#(start_position,end_position)
print('1st row 1st element',arrays[0,0])
print('1st row last element',arrays[0,3])
print('3rd row 2nd element ',arrays[2,1])
print('2rd row 3nd element ',arrays[1,2])

1st row 1st element 1
1st row last element 4
3rd row 2nd element  10
2rd row 3nd element  7


In [9]:
#geting sub elements of array
#(row,coloum)
print('1st row',arrays[0:1])
print('3rd row',arrays[2:3])
#[start_position_row:end_position_row,start_position_coloum:end_position_coloum]
print('2nd row 1st 2 elements',arrays[1,:2])
print('3nd row last 2 elements',arrays[2,2:])

1st row [[1 2 3 4]]
3rd row [[ 9 10 11 12]]
2nd row 1st 2 elements [5 6]
3nd row last 2 elements [11 12]


In [10]:
#size of 2-D array
print('size',arrays.shape)

size (3, 4)


In [11]:
#sum min max of array
#1+2+3+4=10
#2 +6+  10=26
#9+ 10+ 11+ 12=42
print(arrays.sum(axis=1))
print('sum of 1st row',arrays[0:1].sum())

[10 26 42]
sum of 1st row 10


In [12]:
#sum min max of array
#1+5+9=15
#5 +6+  7+  8=18
#3+ 7+ 11=21
#4+ 8+ 12=24
print(arrays.sum(axis=0))

[15 18 21 24]


In [13]:
#reading data from csv and storing 
data=np.genfromtxt('data.csv',delimiter=';', skip_header=1)
header=np.genfromtxt('data.csv',delimiter=';',dtype=None)

In [14]:
header=header[0:1,:]
print(header)
print(data[0:2,:])

[[b'"fixed acidity"' b'"volatile acidity"' b'"citric acid"'
  b'"residual sugar"' b'"chlorides"' b'"free sulfur dioxide"'
  b'"total sulfur dioxide"' b'"density"' b'"pH"' b'"sulphates"'
  b'"alcohol"' b'"quality"']]
[[  7.4      0.7      0.       1.9      0.076   11.      34.       0.9978
    3.51     0.56     9.4      5.    ]
 [  7.8      0.88     0.       2.6      0.098   25.      67.       0.9968
    3.2      0.68     9.8      5.    ]]
